# Generated by Django 3.2.13 on 2022-05-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banhmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banhmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping1', models.CharField(max_length=100)),
                ('topping2', models.CharField(max_length=100)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banhmi.size')),
            ],
        ),
    ]
